# Generated by Django 3.0.4 on 2020-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('name', models.CharField(default='', max_length=255, null=True, unique=True)),
                ('email', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default='', null=True)),
                ('otp', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('otp_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('verify_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.NullBooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
    ]
