# Generated by Django 3.0.2 on 2020-03-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSymbol',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default='', max_length=255, null=True, unique=True)),
                ('c_symbol', models.CharField(default='', max_length=255, null=True, unique=True)),
            ],
        ),
    ]
